name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore FinancialTransactionsAPI.sln
      
    - name: Build
      run: dotnet build FinancialTransactionsAPI.sln --no-restore --configuration Release
      
    - name: Test
      run: dotnet test FinancialTransactionsAPI.sln --no-build --configuration Release --verbosity normal --collect:"XPlat Code Coverage"
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        
  security-scan:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run security scan
      run: |
        dotnet list FinancialTransactionsAPI/FinancialTransactionsAPI.csproj package --vulnerable --include-transitive
        
  docker-build:
    runs-on: ubuntu-latest
    needs: [test, security-scan]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t financial-transactions-api:latest -f Dockerfile .
      
    - name: Run Docker container
      run: |
        docker run -d -p 8080:80 --name test-container financial-transactions-api:latest
        sleep 10
        curl -f http://localhost:8080/health || exit 1
        docker stop test-container